# Generated by Django 3.2.6 on 2021-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, default=4, null=True)),
                ('topping', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
